---

- name: Install zabbix_agent
  ansible.builtin.pkgng:
    name: "{{ zabbix_agent_package }}"
    state: present

- name: "Create /etc/rc.conf.d/{{ zabbix_agent_service }}"
  ansible.builtin.template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ zabbix_agent_service }}"
    mode: "0644"

- name: Enable zabbix_agent
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    enabled: yes
