---
# tasks file for ansible-role-zabbix_agent

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create zabbix_agent_conf_d_dir
  ansible.builtin.file:
    path: "{{ zabbix_agent_conf_d_dir }}"
    mode: "0755"
    state: directory

- name: Create zabbix_agent_config_flagments
  ansible.builtin.template:
    src: flagment.j2
    dest: "{{ zabbix_agent_conf_d_dir }}/{{ item['name'] }}"

    # XXX agent reads the files _after_ dropping priv
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: "0600"
  with_items: "{{ zabbix_agent_config_flagments }}"
  notify:
    - Restart zabbix_agent
  when:
    - "item['state'] == 'present'"

- name: Create zabbix_agent_x509_cert_dir
  ansible.builtin.file:
    path: "{{ zabbix_agent_x509_cert_dir }}"
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: "0755"
    state: directory
  when:
    - zabbix_agent_x509_cert_dir | length > 0

- name: Include trombik.x509_certificate
  # XXX `ansible.builtin.include_role` causes `MODULE FAILURE` on Ubuntu
  # (ansible 2.9.6). use `include_role` for now.
  # ansible.builtin.include_role:
  #
  # TODO use `vars`? i.e. make it possible for multiple roles to perform include_role
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#includes-dynamic-re-use
  include_role:
    name: trombik.x509_certificate
  vars:
    x509_certificate: "{{ zabbix_agent_x509_certificates }}"
  when:
    - zabbix_agent_x509_certificates
    - zabbix_agent_x509_certificates | length > 0

- name: Create zabbix_agent_pid_dir
  ansible.builtin.file:
    path: "{{ zabbix_agent_pid_dir }}"
    mode: '0755'
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    state: directory

- name: Create zabbix_agent_log_dir
  ansible.builtin.file:
    path: "{{ zabbix_agent_log_dir }}"
    mode: '0755'
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    state: directory

- name: Remove zabbix_agent_config_flagments
  ansible.builtin.file:
    path: "{{ zabbix_agent_conf_d_dir }}/{{ item['name'] }}"
    state: absent
  with_items: "{{ zabbix_agent_config_flagments }}"
  notify:
    - Restart zabbix_agent
  when:
    - "item['state'] == 'absent'"

- name: Create zabbix_agent_conf_file
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: "{{ zabbix_agent_conf_file }}"
    mode: '0640'
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
  notify: Restart zabbix_agent

- name: Start zabbix_agent
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    enabled: true
    state: started
